# docker-compose.dev.yml

version: '3.8'

services:
  # 1. Spring Boot Application
  backend:
    container_name: foodtruck-backend
    image: ${DOCKER_USERNAME}/foodtruck-be:dev  # GitHub Actions에서 빌드한 이미지
    restart: always
    ports:
      - "80:8080"  # 외부 80포트 -> 내부 8080포트 연결 (http://IP 로 접속 가능)
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/foodtruck_db?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD} # .env 또는 실행 시 주입
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    depends_on:
      - mysql
      - redis
    networks:
      - foodtruck-network

  # 2. Redis
  redis:
    image: redis:latest
    container_name: foodtruck-redis
    restart: always
    command: redis-server --appendonly yes
    networks:
      - foodtruck-network

  # 3. MySQL
  mysql:
    image: mysql:8.0
    container_name: foodtruck-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: foodtruck_db
      TZ: Asia/Seoul
    ports:
      - "3306:3306" # 개발 편의상 외부 접속 허용 (보안 중요시 제거)
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/data:/var/lib/mysql # EC2 내부에 데이터 영구 저장
    networks:
      - foodtruck-network

networks:
  foodtruck-network:
    driver: bridge